spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:service;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  jpa:
    generate-ddl: true
    open-in-view: false
  data:
    redis:
      host: localhost

httpclient:
  response-timeout-seconds: 2
  connection-timeout-millis: 3000